sample_rate: 16000
timesteps: 128
repeat: 1
dropout: 0.0
kernel_size_factor: 1.0
labels: []

preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  window_size: 0.025
  window_stride: 0.01
  window: hann
  features: 64
#  n_mels: 64
#  n_mfcc: 64
  n_fft: 512
  stft_conv: true

spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 2
  freq_width: 15
  time_width: 25
  rect_masks: 5
  rect_time: 25
  rect_freq: 15

crop_or_pad_augment:
  _target_: nemo.collections.asr.modules.CropOrPadSpectrogramAugmentation
  audio_length: 128

encoder:
  _target_: nemo.collections.asr.modules.ConvASREncoder
  feat_in: 64
  activation: relu
  conv_mask: true
  jasper:
  - filters: 128
    repeat: 1
    kernel:
    - 11
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
    separable: true
    kernel_size_factor: 1.0
  - filters: 64
    repeat: 1
    kernel:
    - 13
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    kernel_size_factor: 1.0
  - filters: 64
    repeat: 1
    kernel:
    - 15
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    kernel_size_factor: 1.0
  - filters: 64
    repeat: 1
    kernel:
    - 17
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    kernel_size_factor: 1.0
  - filters: 128
    repeat: 1
    kernel:
    - 29
    stride:
    - 1
    dilation:
    - 2
    dropout: 0.0
    residual: false
    separable: true
    kernel_size_factor: 1.0
  - filters: 128
    repeat: 1
    kernel:
    - 1
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false

decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoderClassification
  feat_in: 128
  return_logits: true
  pooling_type: avg

target: nemo.collections.asr.models.classification_models.EncDecClassificationModel